name: Node.js Docker Deploy

on:
  push:
    branches:
      - gui

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build and Dockerize
        run: |
          docker build -t studentCompanion-image .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push your-docker-image-name

      - name: SSH into the server and deploy
        uses: appleboy/ssh-action@v2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Stop and remove previous Docker container
            docker stop studentCompanion || true
            docker rm studentCompanion || true

            # Pull the latest Docker image
            docker pull studentCompanion-image

            # Run the Docker container
            docker run -d --name studentCompanion -p 5173:5173 studentCompanion-image
